name: Python CI/CD Pipeline

on: [push, pull_request]

jobs:
  test:
    name: Test and Lint
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run flake8 linter
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        
    - name: Run tests with pytest
      run: |
        pytest --cov=. --cov-report=xml --html=report.html --self-contained-html
        
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      
    - name: Upload test report
      uses: actions/upload-artifact@v4
      with:
        name: pytest-report
        path: report.html
        retention-days: 5